# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# REST

api_list:
  url: /api/:model
  class: sfRequestRoute
  param: { module: api, action: list, sf_format: json }
  requirements:
    sf_method: [GET]

# ws_create:
#   url: /rest/:model.:sf_format
#   class: sfRequestRoute
#   param: { module: webservice, action: create, sf_format: xml }
#   requirements:
#     sf_method: [POST]

# ws_get:
#   url: /rest/:model/:id.:sf_format
#   class: sfRequestRoute
#   param: { module: webservice, action: get, sf_format: xml, column: id }
#   requirements:
#     id: \d+
#     sf_method: [GET]

# ws_update:
#   url: /rest/:model/:id.:sf_format
#   class: sfRequestRoute
#   param: { module: webservice, action: update, sf_format: xml, column: id }
#   requirements:
#     id: \d+
#     sf_method: [PUT]

# ws_delete:
#   url: /rest/:model/:id.:sf_format
#   class: sfRequestRoute
#   param: { module: webservice, action: delete, sf_format: xml, column: id }
#   requirements:
#     id: \d+
#     sf_method: [DELETE]

# default rules
homepage:
  url:   /
  param: { module: show, action: last }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
