# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        TV web app
    #description:  An awesome TV Shows web app
    #keywords:     tv show
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css]

  javascripts:    [vendor/modernizr-2.6.2.min.js, vendor/jquery-1.9.1.min.js, vendor/backbone-min.js, main.js]

  has_layout:     true
  layout:         layout
