<?php



/**
 * Skeleton subclass for performing query and update operations on the 'episode' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.4 on:
 *
 * Fri Jun 28 19:49:08 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class EpisodePeer extends BaseEpisodePeer {

} // EpisodePeer
